### ISSUE TITLE
The icons corresponding to the music player actions are selectable

### ISSUE THREAD

**Issue by rdb-github** [rdb-github/festplayer#8]
**Bug** 
All of the icons under .material_icons are selectable, as if they were actual text.

**Intended behaviour** 
These buttons shouldn't be selectable.

**Operating system/Browser** 
Bug confirmed on Chromium 73 for Debian 9 and Chrome 74 for Android 8.0.0 (Oreo).

**Comment by rdb-github** [comment]
**Cause**
The icons are part of a fontpack, material-icons, made by Google. They are selectable because they are text.

**Fix** 
```css
.material-icons{
user-select:none;
-ms-user-select:none;
-webkit-user-select:none;
-moz-user-select:none
}
```

**Estimated fix release** 
Within next 10 commits.
